import Head from "next/head";
import SeSlider from "@/components/home/SeSlider";
import SecondInfo from "@/components/info/SecondInfo";
import StockInfo from "@/components/stockInfo/StockInfo";
import Board from "@/components/board/Board";
import Footer from "@/components/footer/Footer";
import axios from "axios";
import { useState } from "react";
import FBanner from "@/components/fbanner/FBanner";
import Navigation from "@/components/nav/Navigation";
import ProfitIncome from "@/components/profitIncome/ProfitIncome";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <meta name="viewport" content="width=device-width, initial-scale=1.0" /> */}
      </Head>
      <main id="home" style={{ backgroundColor: "#fff" }}>
        <Navigation />
        <FBanner />
        <SeSlider />
        <SecondInfo />
        <ProfitIncome />

        <StockInfo />
        <Board />

        <Footer />
      </main>
    </>
  );
}
