import Head from "next/head";
import SeSlider from "@/components/home/SeSlider";
import SecondInfo from "@/components/info/SecondInfo";
import StockInfo from "@/components/stockInfo/StockInfo";
import Board from "@/components/board/Board";
import Footer from "@/components/footer/Footer";
import axios from "axios";
import { useState } from "react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
       
      </Head>
      <main style={{ backgroundColor: "#fff" }}>
        <SeSlider />
        <SecondInfo />
        <StockInfo />
        <Board />
        <Footer />
      </main>
    </>
  );
}
